<a href="https://colab.research.google.com/github/abduvokhid25/numpy/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy



In [5]:
import numpy as np
arr = np.array([1,3,4,5])
print("numpy array:", arr)
arr.shape


numpy array: [1 3 4 5]


(4,)

In [6]:
arr2 = np.array([[1,3,4,5], [4,1,3,2]])
print("numpy array2:", arr)

arr2.shape

numpy array2: [1 3 4 5]


(2, 4)

In [ ]:
#dtype
a = np.array([1,4,6,3])
print (a.dtype)

In [11]:
# reshape
a = np.array([1,3,4,5,2,4])
b = a.reshape(2, 3)
print('shaped array:', b)

shaped array: [[1 3 4]
 [5 2 4]]


In [12]:
#astype

a = np.array([3,5,3,5,3])
b = a.astype(float)
print('float:', b)

float: [3. 5. 3. 5. 3.]


In [14]:
# np.zero(), np.one()  => dummy data

z = np.zeros((2,3))
o = np.ones((2, 3))

print('zeros:', z)
print('ones:', 0)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: 0


In [15]:
#ndim

a = np.array([[2,3,5], [4,2,3]])
print('ndim:', a.ndim)


ndim: 2


In [21]:
# arrange()
a = np.arange(1, 6)
print("arange:", a)

arange: [1 2 3 4 5]


In [ ]:
# sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4])

print("sum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("min:", a.min())

In [ ]:
# flatten()
a = np.array([[1, 2], [3, 4]])
print('flatten:', a.flatten())

In [ ]:
# T (Transpose)
a = np.array([[1, 2], [3, 4]])
print("transpose:", a.T)

In [22]:
# dot() @
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print("dot/multiplication:", a.dot(b))

dot/multiplication: [[ 4  4]
 [10  8]]


In [23]:
# random.rand()

a = np.random.rand(2, 5)
print('random.rand:', a)

random.rand: [[0.31760407 0.19371424 0.81614034 0.29137723 0.01085069]
 [0.43328403 0.70024136 0.46016544 0.30830331 0.31691096]]
